ALTER TABLE `CON_DETAIL_RECORD` ADD PRIMARY KEY (`rec_id`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `FIRST_NAME_IDX`(`rec_name_first_name`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `LAST_NAME_IDX`(`rec_name_last_name`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `MIDDLE_NAME_IDX`(`rec_name_middle`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `GENDER_IDX`(`rec_name_gender`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `COUNTRY_IDX`(`rec_country`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `CITY_IDX`(`rec_city`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `STATE_IDX`(`rec_state`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `ZIP_IDX`(`rec_zip`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `ZIP4_IDX`(`rec_zip4`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `ADDR_NUMBER_IDX`(`rec_addr_number`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `ADDR_PREDIR_IDX`(`rec_addr_predir`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `ADDR_STREET_IDX`(`rec_addr_street`);
ALTER TABLE `CON_DETAIL_RECORD` ADD INDEX `ADDR_SUFFIX_IDX`(`rec_addr_suffix`);

ALTER TABLE `DETAIL_RECORD` ADD PRIMARY KEY (`rec_id`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `FIRST_NAME_IDX`(`rec_name_first_name`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `LAST_NAME_IDX`(`rec_name_last_name`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `MIDDLE_NAME_IDX`(`rec_name_middle`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `GENDER_IDX`(`rec_name_gender`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `COUNTRY_IDX`(`rec_country`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `CITY_IDX`(`rec_city`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `STATE_IDX`(`rec_state`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `ZIP_IDX`(`rec_zip`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `ZIP4_IDX`(`rec_zip4`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `ADDR_NUMBER_IDX`(`rec_addr_number`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `ADDR_PREDIR_IDX`(`rec_addr_predir`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `ADDR_STREET_IDX`(`rec_addr_street`);
ALTER TABLE `DETAIL_RECORD` ADD INDEX `ADDR_SUFFIX_IDX`(`rec_addr_suffix`);

ALTER TABLE `CON_CREATION_LAST_UPDATED` ADD INDEX `REC_ID_IDX`(`rec_id`);

ALTER TABLE `CREATION_LAST_UPDATED` ADD INDEX `REC_ID_IDX`(`rec_id`);

ALTER TABLE `CON_REC_EMAIL` ADD INDEX `REC_ID_IDX`(`rec_id`);
ALTER TABLE `CON_REC_EMAIL` ADD INDEX `EMAIL_IDX`(`email`);

ALTER TABLE `REC_EMAIL` ADD INDEX `REC_ID_IDX`(`rec_id`);
ALTER TABLE `REC_EMAIL` ADD INDEX `EMAIL_IDX`(`email`);

ALTER TABLE `CON_REC_FAX` ADD INDEX `REC_ID_IDX`(`rec_id`);
ALTER TABLE `CON_REC_FAX` ADD INDEX `REC_FAX_NUMBER_IDX`(`rec_fax_number`);
ALTER TABLE `CON_REC_FAX` ADD INDEX `REC_FAX_EXT_IDX`(`rec_fax_ext`);


ALTER TABLE `REC_FAX` ADD INDEX `REC_ID_IDX`(`rec_id`);
ALTER TABLE `REC_FAX` ADD INDEX `REC_FAX_NUMBER_IDX`(`rec_fax_number`);
ALTER TABLE `REC_FAX` ADD INDEX `REC_FAX_EXT_IDX`(`rec_fax_ext`);

ALTER TABLE `CON_REC_PHONE` ADD INDEX `REC_ID_IDX`(`rec_id`);
ALTER TABLE `CON_REC_PHONE` ADD INDEX `REC_PHONE_NUMBER_IDX`(`rec_phone_number`);
ALTER TABLE `CON_REC_PHONE` ADD INDEX `REC_PHONE_EXT_IDX`(`rec_phone_ext`);

ALTER TABLE `REC_PHONE` ADD INDEX `REC_ID_IDX`(`rec_id`);
ALTER TABLE `REC_PHONE` ADD INDEX `REC_PHONE_NUMBER_IDX`(`rec_phone_number`);
ALTER TABLE `REC_PHONE` ADD INDEX `REC_PHONE_EXT_IDX`(`rec_phone_ext`);

ALTER TABLE `REC_CONTACT` ADD INDEX `REC_ID_BUS_IDX`(`rec_id_bus`);
ALTER TABLE `REC_CONTACT` ADD INDEX `REC_ID_CON_IDX`(`rec_id_con`);

ALTER TABLE `DOMAIN_NAMES` ADD INDEX `REC_ID_IDX`(`rec_id`);
ALTER TABLE `DOMAIN_NAMES` ADD INDEX `DOMAIN_NAME_IDX`(`domain_name`);
