ALTER TABLE CON_CREATION_LAST_UPDATED DISABLE KEYS;

ALTER TABLE CREATION_LAST_UPDATED DISABLE KEYS;

ALTER TABLE CON_REC_EMAIL DISABLE KEYS;

ALTER TABLE REC_EMAIL DISABLE KEYS;

ALTER TABLE CON_REC_FAX DISABLE KEYS;

ALTER TABLE REC_FAX DISABLE KEYS;

ALTER TABLE CON_REC_PHONE DISABLE KEYS;

ALTER TABLE REC_PHONE DISABLE KEYS;

ALTER TABLE REC_CONTACT DISABLE KEYS;

ALTER TABLE DETAIL_RECORD DISABLE KEYS;

ALTER TABLE DOMAIN_NAMES DISABLE KEYS;

ALTER TABLE CON_DETAIL_RECORD DISABLE KEYS;

ALTER TABLE DETAIL_RECORD DISABLE KEYS;
