ALTER TABLE CON_CREATION_LAST_UPDATED ENABLE KEYS;

ALTER TABLE CREATION_LAST_UPDATED ENABLE KEYS;

ALTER TABLE CON_REC_EMAIL ENABLE KEYS;

ALTER TABLE REC_EMAIL ENABLE KEYS;

ALTER TABLE CON_REC_FAX ENABLE KEYS;

ALTER TABLE REC_FAX ENABLE KEYS;

ALTER TABLE CON_REC_PHONE ENABLE KEYS;

ALTER TABLE REC_PHONE ENABLE KEYS;

ALTER TABLE REC_CONTACT ENABLE KEYS;

ALTER TABLE DETAIL_RECORD ENABLE KEYS;

ALTER TABLE DOMAIN_NAMES ENABLE KEYS;

ALTER TABLE CON_DETAIL_RECORD ENABLE KEYS;

ALTER TABLE DETAIL_RECORD ENABLE KEYS;
